global:
  scrape_interval: 5s

# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets:
#       - alertmanager:9093

scrape_configs:
  - job_name: 'swingsight_app'
    static_configs:
      - targets: ['swingsight:5050']

# rule_files:
#   - alert.rules