---
- name: Capture alertmanager alerts
  hosts: localhost
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5050
        data_alerts_path: alerts
        data_host_path:
        data_path_separator: .
        skip_original_data: true
      filters:
        - cloin.eda.poster:
            webhook_url:

  rules:

    - name: Dispatch RangeRoamer
      condition: |
        event.alert.labels.alertname == "Golf ball alert" and
        event.alert.labels.job == "swingsight_app" and
        event.alert.status == "firing"
      action:
        run_playbook:
          name: /playbooks/am_dispatch_rangeroamer.yml

    - name: RangeRoamer completed
      condition: |
        event.alert.labels.alertname == "Golf ball alert" and
        event.alert.labels.job == "swingsight_app" and
        event.alert.status == "resolved"
      action:
        debug:

    - name: SSL cert expiring
      condition: |
        event.alert.labels.alertname == "SSL expiry" and
        event.alert.labels.job == "blackbox" and
        event.alert.status == "firing"
      action:
        debug: