---
- name: Respond to Datadog events
  hosts: all
  sources:
    - cloin.datadog.dd_events:
        app_key: "{{ datadog_app_key }}"
        api_key: "{{ datadog_api_key }}"
        api_url: "{{ datadog_events_endpoint }}"
        interval: 10

  rules:
    - name: Catch Incidents events
      condition: event.source == "Incidents"
      action:
        debug:

    - name: SwingSight - Dispatch RangeRoamer
      condition: event.source == "Monitor Alert" and event.title is search("swingsight",ignorecase=true) and event.title is search("Triggered",ignorecase=true)
      action:
        debug:

    - name: SwingSight - Monitor resolved
      condition: event.source == "Monitor Alert" and event.title is search("swingsight",ignorecase=true) and event.title is search("Recovered",ignorecase=true)
      action:
        debug:

    - name: Catch Monitor Alert events
      condition: event.source == "Monitor Alert"
      action:
        debug:

    - name: Catch all other events
      condition: event.id is defined
      action:
        debug:
